---

- name: bkp_tcl
  hosts: tests

  tasks:
  - name: backup themecloud script
    local_action: ansible.builtin.command /root/snap/semaphore/common/backup-script/checkname.sh  {{ inventory_hostname }}
    register: shell_result
  - debug: 
      var: shell_result.stdout_lines
