---

- name: bkp_tcl
  hosts: tests

  tasks:
  - name: backup themecloud script
    local_action: ansible.builtin.command /home/fabrice/backup-script/tcl_backup.sh {{ hostvars[groups.ansible_port] }}
    register: shell_result
  - debug: 
      var: shell_result.stdout_lines
